# Generated by Django 4.0 on 2022-07-22 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_size_mb', models.IntegerField()),
                ('video_length', models.IntegerField()),
                ('video_type', models.CharField(max_length=5)),
                ('total_charge', models.IntegerField()),
            ],
        ),
    ]
