# Generated by Django 4.0 on 2022-07-22 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videocharge', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videocharge',
            name='total_charge',
        ),
    ]
